export const PRINTER_LIST_SUCCESS = 'PRINTER_LIST_SUCCESS';
export const PRINTER_LIST_FAIL = 'PRINTER_LIST_FAIL';
export const ADD_PRINTER_SUCCESS = 'ADD_PRINTER_SUCCESS';
export const ADD_PRINTER_FAIL = 'ADD_PRINTER_FAIL';
